-- AlterTable
ALTER TABLE "HrTask" ADD COLUMN IF NOT EXISTS "requiresPhoto" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "photoUrl" TEXT;

-- AlterTable
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "requiresPhoto" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "photoUrl" TEXT;
